### ISSUE TITLE
The Autocomplete shortcuts for the LEARN IDE are accessible

### ISSUE THREAD

**Issue by Martyn-Conkling** [learn-co-curriculum/text-formatting#6]
In the tutorial video, the instructor uses helpful shortcuts in sublime text editor to auto -complete some basic formatting elements.  If you are using the LEARN IDE, YOU CAN DO THIS TO.  Simply press Alt so that the menu bar pops up.  Then go to Packages, then Command Pallette, then click toggle, and search for toggle autocomplete.  Then you can type html and click the autocomplete and it will fill in the basic html formatting elements for you in your text document that you have open.

**Comment by curiositypaths** [comment]
Thank you for the suggestion. We updated the README to provide Learn IDE applicable directions.

As always thanks for contributing.
